version: '2'

services:
  mysql:
    image: mysql:5.7
    container_name: kick_up.mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: kick_up
      MYSQL_USER: kick_up
      MYSQL_PASSWORD: 1
    ports:
    - 3307:3306
  adminer:
    image: adminer
    container_name: kick_up.adminer
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: 1
    ports:
    - 8080:8080
    links:
    - mysql
    logging:
      driver: none
  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example