export const GET_ERRORS = 'GET_ERRORS';

export const AUTHENTICATION_START = 'AUTHENTICATION_START';
export const AUTHENTICATION_STORE_USER = 'AUTHENTICATION_STORE_USER';
export const AUTHENTICATION_USER_HAS_AUTHENTICATED = 'AUTHENTICATION_USER_HAS_AUTHENTICATED';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';

export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';

// Main page;
export const LOAD_INDEX_POSTS = 'LOAD_INDEX_POSTS';

// Rooms;
export const STORE_ROOMS = 'STORE_ROOMS';
export const SET_LOADING_ROOMS_STATUS = 'SET_LOADING_ROOMS_STATUS';
export const STORE_ROOM_DETAILS = 'STORE_ROOM_DETAILS';