export const GET_ERRORS = 'GET_ERRORS';

export const AUTHENTICATION_START = 'AUTHENTICATION_START';
export const AUTHENTICATION_STORE_USER = 'AUTHENTICATION_STORE_USER';
export const AUTHENTICATION_USER_HAS_AUTHENTICATED = 'AUTHENTICATION_USER_HAS_AUTHENTICATED';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';

export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';

// Main page;
export const LOAD_INDEX_POSTS = 'LOAD_INDEX_POSTS';
export const LOAD_INDEX_POSTS = 'LOAD_INDEX_POSTS';
//userProfile
export const USER_PROFILE_DATA = 'USER_PROFILE_DATA';

//editUserProfile
export const UPDATE_EDIT_USER_PROFILE = 'UPDATE_EDIT_USER_PROFILE';
export const UPDATE_INPUT_VALUE_EDIT_PROFILE = 'UPDATE_INPUT_VALUE_EDIT_PROFILE';

