export const GET_ERRORS = 'GET_ERRORS';
export const AUTHENTICATION_START = 'AUTHENTICATION_START';
export const AUTHENTICATION_STORE_USER = 'AUTHENTICATION_STORE_USER';
export const AUTHENTICATION_USER_HAS_AUTHENTICATED = 'AUTHENTICATION_USER_HAS_AUTHENTICATED';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
